import Head from "next/head";
import Header from "../src/components/Header";
export default function Home() {
  return (
    <>
      <Head>
        <title>NEXT QUOTE APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
    </>
  );
}
